---
- name: Ensure that the necessary directories exist
  file: path={{ atom_path }} state=directory owner={{ atom_user }} group={{ atom_group }}
  sudo: yes
  with_items:
    - "{{ atom_path }}"
    - "{{ atom_path }}/log"

- name: Cleanup cache/ directory
  command: rm -rf {{ atom_path }}/cache/*
  sudo: yes # Just in case...

- name: Relax permissions # ... so we can stop using sudo
  command: "chown -R {{ ansible_user_id }} {{ atom_path }}"
  tags: assets
  sudo: yes

- name: Pull new code
  git: update=yes
       force=yes
       repo={{ atom_repository.url }}
       version={{ atom_repository.version }}
       dest={{ atom_path }}
       accept_hostkey=yes
  notify:
    - Clear sf_cache
    - Reload php5-fpm

- name: Install configuration files
  template: src="{{ item.src }}" dest="{{ item.dest }}"
  with_items:
    - { src: "config.php.j2", dest: "{{ atom_path }}/config/config.php" }
    - { src: "app.yml.j2", dest: "{{ atom_path }}/apps/qubit/config/app.yml" }
    - { src: "factories.yml.j2", dest: "{{ atom_path }}/apps/qubit/config/factories.yml" }
    - { src: "settings.yml.j2", dest: "{{ atom_path }}/apps/qubit/config/settings.yml" }
    - { src: "propel.ini.j2", dest: "{{ atom_path }}/config/propel.ini" }
    - { src: "search.yml.j2", dest: "{{ atom_path }}/config/search.yml" }
  notify:
    - Clear sf_cache
    - Reload php5-fpm

- name: Uploads symlink
  file: state=link src={{ atom_uploads_symlink }} path="{{ atom_path }}/uploads" force=yes
  sudo: yes
  when: atom_uploads_symlink is defined
- name: Uploads directory
  file: state=directory path="{{ atom_path }}/uploads" owner={{ atom_user }} group={{ atom_group }}
  sudo: yes
  when: atom_uploads_symlink is undefined

- name: Fix permissions
  shell: "chown -R {{ item.owner }}:{{ item.group }} {{ item.path }}"
  sudo: yes
  with_items: atom_filesystem_permissions
  ignore_errors: yes
