---

# Compile available themes
- name: "Find themes"
  shell: "find {{ atom_path }}/{{ atom_path_extra }}/plugins -name Makefile | sed -r 's/Makefile//g'"
  register: theme_makefiles
  when: "atom_compile_all_themes|bool"

- name: "Compile themes"
  shell: "cd {{ item }} && make"
  with_items: "{{ theme_makefiles.stdout_lines }}"
  when: "atom_compile_all_themes|bool"

- name: "Update database"
  command: "php symfony tools:upgrade-sql -B"
  args:
    chdir: "{{ atom_path }}/{{ atom_path_extra }}"
  when: "atom_upgrade_sql|bool"

- name: "Build nested set"
  command: "php symfony propel:build-nested-set"
  args:
    chdir: "{{ atom_path }}/{{ atom_path_extra }}"
  when: "atom_fix_data|bool"

- name: "Generate slugs"
  command: "php symfony propel:generate-slugs"
  args:
    chdir: "{{ atom_path }}/{{ atom_path_extra }}"
  when: "atom_fix_data|bool"

- name: "Clear cache"
  command: "php symfony cache:clear"
  args:
    chdir: "{{ atom_path }}/{{ atom_path_extra }}"
  notify:
    - "Reload PHP service"

# stdout is ignored, not very useful and too verbose (--quiet opt would be nice)
- name: "Populate search index"
  shell: "php symfony search:populate 1>/dev/null"
  args:
    chdir: "{{ atom_path }}/{{ atom_path_extra }}"
  ignore_errors: "yes" # segfault in php7, not sure yet why!
  environment: "{{ atom_pool_php_envs }}"
  when: "atom_populate_index|bool"
