---
- name: Add repo ppa:archivematica/externals-dev and update cache
  apt_repository: "repo=ppa:archivematica/externals-dev update_cache=yes"

- name: Install AtoM dependencies
  apt: "pkg={{ item }} state=present"
  with_items:
    - imagemagick
    - ghostscript
    - poppler-utils
    - ffmpeg

#
# Packages required for the build
#

- name: Add nodejs PPA from Chris Lea
  apt_repository: repo="{{ item }}" state=present
  with_items:
    - "ppa:chris-lea/node.js"

- name: Install packages required for the build process
  apt: pkg="{{ item }}" state=present
  with_items:
    - git
    - nodejs
    - python-pip
    - make

- name: Install sphinx globally using pip
  pip: name={{ item }}
  with_items:
    - sphinx
    - sphinxcontrib-httpdomain

- name: Install npm global dependencies (also required during the build)
  npm: name={{ item }} global=yes
  with_items:
    - grunt-cli
    - less@1.3.3
