---

- name: "Install AtoM dependencies"
  yum:
    name: 
      - "ImageMagick"       # ↓ AtoM dependencies
      - "ghostscript"       #
      - "poppler-utils"     #
      - "ffmpeg"            #
      - "git"               # ↓ Build dependencies
      - "rh-nodejs6"        #
      - "make"              #
      - "gcc"               #
      - "python-pip"        #
      - "python-setuptools" #
      - "python2-cryptography"
      - "java-1.8.0-openjdk-headless" # needed by FOP
    state: "latest"
    
- name: "Install Sphinx"
  pip:
    name:
      - "sphinx==1.8.5"
      - "sphinxcontrib-httpdomain==1.7.0"
      - "sphinx_rtd_theme==0.5.0"
    state: "present"
  environment:
    http_proxy: "{{http_proxy}}"
    https_proxy: "{{https_proxy}}"

#don't quote the shell command, or it won't work (also need to escape the <)
- name: "Install npm (SCL) global dependencies (also required during the build)"
  shell: scl enable rh-nodejs6 'npm install -g grunt-cli less@\<2.0.0'
  environment:
    http_proxy: "{{http_proxy}}"
    https_proxy: "{{https_proxy}}"
