---

- name: "Add external repository keys"
  apt_key:
    url: "{{ item }}"
    state: "present"
  with_items:
    - "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"

- name: "Add external repositories"
  apt_repository:
    repo: "{{ item }}"
    update_cache: "yes"
  with_items:
    - "ppa:archivematica/externals-dev"
    - "deb https://deb.nodesource.com/node_5.x trusty main"
    - "ppa:git-core/ppa"

- name: Install AtoM dependencies
  apt:
    pkg: "{{ item }}"
    state: "latest"
  with_items:
    - "imagemagick"    # ↓ AtoM dependencies
    - "ghostscript"    #
    - "poppler-utils"  #
    - "ffmpeg"         #
    - "git"            # ↓ Build dependencies
    - "nodejs"         #
    - "make"           #
    - "python-pip"     #

- name: "Install Sphinx"
  pip:
    name: "{{ item }}"
    state: "latest"
  with_items:
    - "sphinx"
    - "sphinxcontrib-httpdomain"

- name: "Install npm global dependencies (also required during the build)"
  npm:
    name: "{{ item }}"
    global: "yes"
  with_items:
    - "grunt-cli"
    - "less@<2.0.0"
