---

- name: "Include OS specific variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_version}}.yml"
    - "{{ ansible_distribution }}.yml"
  tags: "always"

- name: "Install PHP packages"
  become: "true"
  apt:
    pkg: "{{ item }}"
    state: "latest"
    update_cache: "yes"
    cache_valid_time: "3600"
    force: "yes"
  with_items: "{{ php_packages }}"

- name: "Remove default www pool"
  file:
    state: "absent"
    path: "/etc/php/{{ php_version }}/fpm/pool.d/www.conf"
  notify:
    - "Restart PHP service"

- name: "Install pool configuration file"
  template:
    src: "etc/php/{{ php_version }}/fpm/pool.d/atom.conf"
    dest: "/etc/php/{{ php_version }}/fpm/pool.d/atom.conf"

# See https://bugs.launchpad.net/ubuntu/+source/php5/+bug/1272788
- name: "Fix php5-fpm upstart"
  lineinfile:
    dest: "/etc/init/php5-fpm.conf"
    line: "reload signal USR2"
  when: "ansible_distribution_version | version_compare('14.04', '==')"
