---

- name: "Enable AtoM plug-ins"
  command: "php symfony tools:atom-plugins add {{ item }}"
  args:
    chdir: "{{ atom_path }}"
  with_items: "{{ atom_plugins }}"
  environment: "{{ atom_pool_php_envs }}"

- name: "Copy elasticsearch plugins"
  command: "cp -rf {{ atom_path }}/plugins/arElasticSearchPlugin/scripts /etc/elasticsearch/"
  become: "yes"
  become_user: "root"
  when: "atom_drmc_es_scripts is defined and atom_drmc_es_scripts|bool"
  notify: "Restart Elasticsearch"
