---

# Note that this file is included with the following in main.yml 
#  so no need to put in each task: 
#    become_user: "{{ atom_user }}"
#    environment: "{{ atom_pool_php_envs }}"


- name: "Enable AtoM plug-ins"
  shell: "php symfony tools:atom-plugins add {{ item }}"
  args:
    chdir: "{{ atom_path }}"
  with_items: "{{ atom_plugins }}"

# copy ES plugins to /etc/elasticsearch (assumes ES running on same server) 
# (copy manually if ES is on a separate backend server)
- name: "Copy elasticsearch plugins"
  command: "cp -rf {{ atom_path }}/plugins/arElasticSearchPlugin/scripts /etc/elasticsearch/"
  become: "yes"
  become_user: "root"
  when: "atom_drmc_es_scripts is defined and atom_drmc_es_scripts|bool"
  notify: "Restart Elasticsearch"
