---

- name: "Stop worker"
  service:
    name: "{{ atom_worker_service_name }}"
    state: "stopped"
  ignore_errors: "yes" # It could be not created yet

- name: "Install atom-worker service (upstart)"
  template:
    src: "etc/init/atom-worker.conf"
    dest: "/etc/init/{{ atom_worker_service_name }}.conf"
  when:
    - ansible_service_mgr != "systemd"

- name: "Install atom-worker service (systemd)"
  template:
    src: "lib/systemd/system/atom-worker.service"
    dest: "/lib/systemd/system/{{ atom_worker_service_name }}.service"
  when:
    - ansible_service_mgr == "systemd"

- name: "Reload systemd daemon"
  command: "systemctl daemon-reload"
  when:
    - ansible_service_mgr == "systemd"

- name: "Start and enable atom-worker service"
  service:
    name: "{{ atom_worker_service_name }}"
    state: "restarted"
    enabled: "yes"
