---

- name: "Stop worker"
  service:
    name: "{{ atom_worker_upstart_service_name }}"
    state: "stopped"
  ignore_errors: "yes" # It could be not created yet

- name: "Create upstart service"
  template:
    src: "etc/init/atom-worker.conf"
    dest: "/etc/init/{{ atom_worker_upstart_service_name }}.conf"

- name: "Start and enable worker"
  service:
    name: "{{ atom_worker_upstart_service_name }}"
    state: "restarted"
    enabled: "yes"
