---

- name: "Restart PHP service"
  service:
    name: "php{{ php_version }}-fpm"
    state: "restarted"

- name: "Reload PHP service"
  service:
    name: "php{{ php_version }}-fpm"
    state: "reloaded"

- name: "Clear sf_cache"
  shell: "php symfony cc"
  args:
    chdir: "{{ atom_path }}"
  become_user: "{{ atom_user }}"
  environment: "{{ atom_pool_php_envs }}"

- name: "Restart smbd"
  service:
    name: "smbd"
    state: "restarted"

- name: "Restart nmbd"
  service:
    name: "nmbd"
    state: "restarted"
