---
- name: Restart php5-fpm
  service: name=php5-fpm state=restarted
  sudo: yes

- name: Reload php5-fpm
  service: name=php5-fpm state=reloaded
  sudo: yes

- name: Clear sf_cache
  shell: "echo help"
#  shell: "php symfony cc"
#  args:
#    chdir: "{{ atom_path }}"
#  sudo: yes
#  sudo_user: "{{ atom_user }}"
