---
- hosts: all

  pre_tasks:
    - name: Include vars
      include_vars: "{{ test_vars_file }}"

    - name: "pre_tasks for Ubuntu"
      include_tasks: "test_pretasks_ubuntu.yml"
      when: ansible_distribution == 'Ubuntu'

  roles:
    - role_under_test
