# {{ ansible_managed }}

all:

  # See http://www.elasticsearch.org/guide/reference/api/bulk.html
  batch_mode: true
  batch_size: 500

  # Elastica API options
  # Full list of available options:
  # https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Client.php#L39
  server:

    # Server defaults to localhost:9200 if omitted
    # It can also be used to configure a cluster of ElasticSearch nodes
    # See more info at: http://ruflin.github.com/Elastica/
    host: {{ atom_es_host }}
    port: {{ atom_es_port }}

    # This will write the JSON request in the file given
    # log: '/tmp/elastica.log'

  # elasticsearch options
  index:

    # This is the name of the index; must be unique
    name: {{ atom_es_index }}

    # List of settings: http://goo.gl/EjQx4
    configuration:

      number_of_shards: 4
      number_of_replicas: 1

      analysis:
        analyzer:
          # This is a special analyzer for autocomplete searches. It's used only
          # in some fields as it can make the index very big.
          autocomplete:
            tokenizer: whitespace
            filter: [lowercase, engram]
        filter:
          engram:
            type: edgeNGram
            min_gram: 3
            max_gram: 10

      # Disable dynamic creation of mappings for unmapped types
      mapper:
        dynamic: false

      # Module settings:
      # http://www.elasticsearch.org/guide/reference/index-modules/
